name: ⚙️ CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - uses: taiga-family/ci/actions/setup/node@v1.36.2

      - name: prepare integration test
        run: |
          rm -rf taiga-ui && git clone https://github.com/taiga-family/taiga-ui.git --single-branch
          cd taiga-ui && npm ci && cd ..

      - run: |
          npm run commitlint
          npm run prettier -- --check
          npm run stylelint
          npm run lint

      - run: |
          npx nx run-many --target build --all

      - name: cleanup
        run: rm -rf taiga-ui

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
